const LANG = {
  en: {
    siteTitle:         '🎨 Kids Art Growth Journal',
    subtitle:          'Capturing every creative spark, one artwork at a time',
    navHome:           'Create',
    navYearly:         'Yearly Collection',
    navPortfolio:      'Portfolio',
    portfolioHeading:  'Art Growth Portfolio',
    portfolioCover:    'Art Growth Record',
    btnDownloadPDF:    'Download PDF',
    pdfGenerating:     'Generating PDF…',
    portfolioEmpty:    'No artworks yet. Add some from the Create tab first.',
    pdfGeneratedOn:    'Generated on',
    pdfArtworks:       'artworks',
    yearlyHeading:     'Yearly Collection',
    yearlyEmpty:       'No artworks this year yet. Go record the first one!',
    uploadHeading:     'Upload a new artwork',
    labelTitle:        'Artwork Name',
    placeholderTitle:  'Give this artwork a name',
    labelArtist:       'Creator',
    placeholderArtist: 'Who created this artwork?',
    labelAge:          'Age',
    placeholderAge:    'Example: 6 years or 6y 3m',
    labelStory:        'Artwork Story',
    placeholderStory:  "What does the child say about this? Write down their thoughts.",
    labelDate:         'Creation Date',
    dropZone:          'Drag or select image',
    btnAdd:            'Save Artwork',
    galleryHeading:    'Timeline',
    emptyState:        "Every artwork tells a story. Start recording your child's first creation.",
    alertNoImage:      'Please select an image first.',
    confirmDelete:     'Remove this drawing from the gallery?',
    byPrefix:          'by',
    deleteTitle:       'Delete',
    deleteLabel:       'Delete drawing',
    btnShare:          'Share',
    sharePageTitle:    'Artwork',
    shareNotFound:     'Artwork not found.',
    shareFooter:       'Recorded with',
    aiHeading:         'Growth Insights',
    aiBtnGenerate:     'Generate Insights',
    aiBtnRegen:        'Regenerate',
    aiLoading:         'Analyzing artworks…',
    aiNotEnough:       'Add at least 2 artworks to generate insights.',
    aiError:           'Generation failed. Please check your API key.',
    apiKeyLabel:       'Claude API Key',
    apiKeyPlaceholder: 'sk-ant-…',
    apiKeyHint:        'Stored locally. Only sent to Anthropic to generate insights.',
    apiKeySet:         'API key saved',
    apiKeyChange:      'Change',
    apiKeySave:        'Save',
    btnShareLink:      '🔗 Share Link',
    btnDownloadImg:    '⬇ Download Image',
    shareToast:        'Link copied. You can share it with friends.',
    navPrevArt:        '← Previous Artwork',
    navNextArt:        'Next Artwork →',
    portfolioCoverSub: "Little Artist's Art Portfolio",
    btnExport:         '📦 Export Data',
    btnImport:         '📥 Import Data',
    importConfirm:     'Importing will overwrite current artworks. Continue?',
    importSuccess:     'Import successful!',
    importError:       'Invalid file. Please select a valid backup file.',
    btnYearlyArtBook:  'Generate Yearly Art Book',
    yearlyArtBookTitle:'Art Book',
    yearlyArtBookPrompt:'Enter a year to export',
    yearlyArtBookInvalid:'Please enter one of the available years.',
    yearlyArtBookEmpty:'No artworks found for that year.',
    btnBackPortfolio:  'Back to Portfolio',
  },
  zh: {
    siteTitle:         '🎨 儿童艺术成长档案',
    subtitle:          '记录孩子每一次创作的闪光',
    navHome:           '创作记录',
    navYearly:         '年度合集',
    navPortfolio:      '作品集',
    portfolioHeading:  '艺术成长作品集',
    portfolioCover:    '艺术成长记录',
    btnDownloadPDF:    '下载PDF',
    pdfGenerating:     '正在生成 PDF…',
    portfolioEmpty:    '暂无作品。请先在主页添加作品。',
    pdfGeneratedOn:    '生成于',
    pdfArtworks:       '幅作品',
    yearlyHeading:     '年度合集',
    yearlyEmpty:       '这一年还没有作品。先去记录第一幅吧。',
    uploadHeading:     '上传孩子的新作品',
    labelTitle:        '作品名称',
    placeholderTitle:  '给这幅作品起个名字',
    labelArtist:       '创作者',
    placeholderArtist: '谁创作了这幅作品？',
    labelAge:          '年龄',
    placeholderAge:    '例如：6岁 或 6岁3个月',
    labelStory:        '作品故事',
    placeholderStory:  '孩子说这幅画是什么？可以记录一下孩子的想法',
    labelDate:         '创作日期',
    dropZone:          '拖拽或选择图片',
    btnAdd:            '保存作品',
    galleryHeading:    '成长时间线',
    emptyState:        '这里会记录孩子的每一次创作。从第一幅作品开始吧。',
    alertNoImage:      '请先选择一张图片。',
    confirmDelete:     '确定要从画廊中删除这幅画吗？',
    byPrefix:          '创作者：',
    deleteTitle:       '删除',
    deleteLabel:       '删除作品',
    btnShare:          '分享',
    sharePageTitle:    '作品',
    shareNotFound:     '未找到该作品。',
    shareFooter:       '由以下应用记录',
    aiHeading:         'AI 成长观察',
    aiBtnGenerate:     '生成成长观察',
    aiBtnRegen:        '重新生成',
    aiLoading:         '正在分析作品…',
    aiNotEnough:       '至少需要 2 幅作品才能生成成长观察。',
    aiError:           '生成失败，请检查 API 密钥是否正确。',
    apiKeyLabel:       'Claude API 密钥',
    apiKeyPlaceholder: 'sk-ant-…',
    apiKeyHint:        '仅保存在本地，只发送给 Anthropic 用于生成观察。',
    apiKeySet:         'API 密钥已保存',
    apiKeyChange:      '更改',
    apiKeySave:        '保存',
    btnShareLink:      '🔗 分享链接',
    btnDownloadImg:    '⬇ 下载图片',
    shareToast:        '链接已复制，可以分享给朋友',
    navPrevArt:        '← 上一幅作品',
    navNextArt:        '下一幅作品 →',
    portfolioCoverSub: '小画家的艺术作品集',
    btnExport:         '📦 导出作品数据',
    btnImport:         '📥 导入作品数据',
    importConfirm:     '导入将覆盖当前作品数据，是否继续？',
    importSuccess:     '导入成功！',
    importError:       '文件无效，请选择正确的备份文件。',
    btnYearlyArtBook:  '生成年度作品画册',
    yearlyArtBookTitle:'艺术画册',
    yearlyArtBookPrompt:'请输入要导出的年份',
    yearlyArtBookInvalid:'请输入可用年份中的一个。',
    yearlyArtBookEmpty:'该年份暂无作品。',
    btnBackPortfolio:  '返回作品集',
  },
};
